### PR TITLE
support cUSD

### PR DESCRIPTION
**Pull request by KarishmaBothara**
Used latest api version and modified all CENNZX RPC calls...

### CODE REVIEW

**Comment by KarishmaBothara** [comment]
Testing all the operations with cUSD on UI (wip)

**Review by eupston — APPROVED** [review]
lgtm. we might want to create UI tests in the future so we don't have to do it manually. could use something like Cypress or selenium

**Comment by KarishmaBothara** [comment]
> lgtm. we might want to create UI tests in the future so we don't have to do it manually. could use something like Cypress or selenium

Ya.. agree
Tested the UI with 18 dp, check add liquidity, make trade (buy/sell) both ways, withdraw liquidity, withdraw all liquidity, add liquidity twice.. all works well... fixed exchange rate display... didn't see this issue earlier as for CENNZ/CPAY used same decimal places..

**Review by holygits — APPROVED** [review]
lgtm, I think we could use smth like dom test for checking component output easily

**Comment by KarishmaBothara** [comment]
this is already add as a part of https://github.com/cennznet/cennzx-ui/pull/39

**Pull request closed without merging**
